apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-app
  namespace: default
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: nginx-blue-service
      previewService: nginx-green-service
      autoPromotionEnabled: true
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: html-volume
          configMap:
            name: nginx-green-configmap