apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-bluegreen-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      version: blue
  strategy:
    blueGreen:
      activeService: nginx-blue-service  # Le service actif, ici la version "blue"
      previewService: nginx-green-service  # Le service en prévisualisation, ici "green"
      autoPromotionEnabled: true  # Désactivation de la promotion automatique pour que nous décidions manuellement
      scaleDownDelaySeconds: 30
  template:
    metadata:
      labels:
        app: nginx
        version: blue  # Le label pour les pods de la version "blue"
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.0  # Version de l'image Nginx pour la version active (blue)
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: nginx-blue-configmap
