apiVersion: v1
kind: Pod
metadata:
  name: nginx-blue
  labels:
    app: nginx-blue
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html-volume
      configMap:
        name: nginx-blue-configmap
