apiVersion: v1
kind: Pod
metadata:
  name: nginx-blue
  labels:
    app: nginx-blue
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 3
  volumes:
    - name: html-volume
      configMap:
        name: nginx-blue-configmap
