apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx-mahdi
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
  restartPolicy: Always
