apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-green-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Blue Page</title>
        <style>
            body {
                background-color: green;
                color: white;
                text-align: center;
                padding-top: 50px;
                font-size: 24px;
            }
        </style>
    </head>
    <body>
    <h1>Welcome to the Green Version!</h1>
    </body>
    </html>
