apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: defaul

resources:
  - resources/configmap/nginx-blue.configmap.yml
  - resources/configmap/nginx-green.configmap.yml
  - resources/services/blue.service.yml
  - resources/services/green.service.yml
  - resources/argo.rollout.yml
  - resources/nginx-pod.yml


commonLabels:
  env: prod