apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default


resources:
  - resources/nginx-blue.configmap.yml
  - resources/nginx-green.configmap.yml
  - resources/nginx-blue-pod.yml
  - resources/nginx-green-pod.yml
  - resources/blue.service.yml
  - resources/green.service.yml