apiVersion: v1
kind: Service
metadata:
  name: nginx-blue-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
    version: blue  # Ce label doit correspondre au label des pods de la version "blue"
  ports:
    - port: 80
      targetPort: 80