apiVersion: v1
kind: Service
metadata:
  name: nginx-green-service
spec:
  selector:
    app: nginx-bluegreen
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
