apiVersion: v1
kind: Service
metadata:
  name: nginx-green-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
    version: green  # Ce label doit correspondre au label des pods de la version "green" une fois que la mise à jour sera faite
  ports:
    - port: 80
      targetPort: 80
